# Basic info
name: "Silvère Héraudeau"
job: 
  en: "Web Engineer"
  fr: "Ingénieur Web"
title: "Silvere Heraudeau"
email: "silvere.heraudeau@gmail.com"
description: 
  en: "A portfolio to talk about the projects I've worked on and what I learned from them."
  fr: "Un portfolio pour parler des projets sur lesquels j'ai travaillé et ce que j'ai appris."
lang: "en"
languages: ["en", "fr"]
language:
  en: "English"
  fr: "Français"
permalink: /:categories/:collection/:title/
env: "prod"
# pics:
#   fr: "/assets/img/flag-fr.svg"
#   en: "/assets/img/flag-us.svg"
#   logo: "/assets/img/logo.svg"

# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://silvereh.github.io/portfolio"
github_username: silvereh

# Languages and syntax highlighting
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include static pages
include: ["_content"]

exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Silvere Heraudeau"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Silvere Heraudeau"

theme: null
